[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.15.0"
aws-sdk-ssm = "0.15.0"
dotenv-parser = "0.1.3"
thiserror = "1.0.31"